global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: nest-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - app-back-blue:3000
          - app-back-green:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: color
        regex: app-back-(.*):3000
        replacement: ${1}

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

rule_files: []
